name: Build Flutter APK

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch: # اس سے آپ دستی طور پر بھی بلڈ چلا سکیں گے

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'

      - name: Get dependencies
        run: flutter pub get
        working-directory: ./ilm-minar-app-v1.4-full-2

      - name: Setup Bitrise Build Cache
        run: |
          curl --retry 5 -sSfL 'https://raw.githubusercontent.com/bitrise-io/bitrise-build-cache-cli/main/install/installer.sh' | sh -s -- -b /tmp/bin -d
          /tmp/bin/bitrise-build-cache activate gradle --cache --cache-push
        working-directory: ./ilm-minar-app-v1.4-full-2
        env:
          BITRISE_BUILD_CACHE_WORKSPACE_ID: ${{ secrets.BITRISE_BUILD_CACHE_WORKSPACE_ID }}
          BITRISE_BUILD_CACHE_AUTH_TOKEN: ${{ secrets.BITRISE_BUILD_CACHE_AUTH_TOKEN }}

      - name: Build release APK
        run: flutter build apk --release
        working-directory: ./ilm-minar-app-v1.4-full-2

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: ilm-minar-app-v1.4-full-2/build/app/outputs/flutter-apk/app-release.apk
